[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Velocidade do monitor serial para você debugar se precisar
monitor_speed = 115200

; Baixa a biblioteca oficial do servo para ESP32 automaticamente
lib_deps = 
	madhephaestus/ESP32Servo @ ^1.1.2